### ISSUE TITLE
Response Web Design

### ISSUE THREAD

**Issue by martinadamsdev** [martinageradams/blog#32]
- [Responsive Design - Tailwind CSS](https://tailwindcss.com/docs/responsive-design)
- [iOS Resolution](https://www.ios-resolution.com)

![Responsive Design Resolution](https://github.com/user-attachments/assets/e33f375d-cf78-4f07-88d7-5c79b888ff11)

```javascript
screens: {
  xs: '375px',
  // sm: '640px', // 默认的 sm
  // md: '768px', // 默认的 md
  // lg: '1024px', // 默认的 lg
  // xl: '1280px', // 默认的 xl
  // '2xl': '1536px', // 默认的 2xl
  '3xl': '1706px',
  '4xl': '1920px',
  '5xl': '2194px',
  '6xl': '2560px',
  '7xl': '3072px',
  '8xl': '3840px',
}
```

```css
@layer utilities {
    /* 默认根字体大小 */
    :root {
        font-size: 16px;
    }

    /*!* sm 断点时 *!*/
    /*@media (min-width: 640px) {*/
    /*    :root {*/
    /*        font-size: 16px; !* 增加 1px *!*/
    /*    }*/
    /*}*/

    /*!* md 断点时 *!*/
    /*@media (min-width: 768px) {*/
    /*    :root {*/
    /*        font-size: 16px; !* 增加 1px *!*/
    /*    }*/
    /*}*/

    /*!* lg 断点时 *!*/
    /*@media (min-width: 1024px) {*/
    /*    :root {*/
    /*        font-size: 16px; !* 增加 1px *!*/
    /*    }*/
    /*}*/

    /*!* xl 断点时 *!*/
    /*@media (min-width: 1280px) {*/
    /*    :root {*/
    /*        font-size: 16px; !* 增加 2px *!*/
    /*    }*/
    /*}*/

    /*!* 2xl 断点时 *!*/
    /*@media (min-width: 1536px) {*/
    /*    :root {*/
    /*        font-size: 16px; !* 增加 2px *!*/
    /*    }*/
    /*}*/

    /*!* 3xl 断点时 *!*/
    /*@media (min-width: 1706px) {*/
    /*    :root {*/
    /*        font-size: 16px; !* 增加 1px *!*/
    /*    }*/
    /*}*/

    /*!* 4xl 断点时 *!*/
    /*@media (min-width: 1920px) {*/
    /*    :root {*/
    /*        font-size: 16px; !* 增加 2px *!*/
    /*    }*/
    /*}*/

    @media (min-width: 2194px) {
        :root {
            font-size: 20px; /* 增加 4px */
        }
    }

    /* 6xl 断点时 */
    @media (min-width: 2560px) {
        :root {
            font-size: 24px; /* 增加 4px */
        }
    }

    /* 7xl 断点时 */
    @media (min-width: 3072px) {
        :root {
            font-size: 28px; /* 增加 4px */
        }
    }

    /* 8xl 断点时 */
    @media (min-width: 3840px) {
        :root {
            font-size: 32px; /* 增加 6px */
        }
    }
}
```
